### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by the-teacher** [TheRole/DummyApp#1]
@sedx 

Проект готов к рефакторингу: https://travis-ci.org/TheRole/DummyApp/builds/47377042

Есть несколько проблем
1. Исходные тесты на rspec 2.14  не заработали под ruby 2.2. Т.к у rspec 2.14 зависимость от модуля, который в новые руби не входит. Хорошо бы мигрировать на rspec 3 https://github.com/TheRole/TheRoleApi/issues/2
2. Я обнаружил, что метод `any?` работает не корректно. Странно, но тесты проходят. Следовательно, тесты написаны на этот метод тоже не корректно. Можно бы поразбираться. https://github.com/TheRole/TheRoleApi/issues/3

**Comment by sedx** [comment]
По поводу второго пункта у меня ряд вопросов:

Во-первых, правльно ли я понял что `any?` может приниать как простой хэш, так и хэш с массивом?
То есть все 4 вызова будут верны:

```
@role.any?(pages: :index)
@role.any?({pages: :index})
@role.any?(pages: [:index,:edit])
@role.any?({pages: [:index,:edit]})
```

Во-вторых, что должен возвращать вызов `@role.any?(pages: [:index, :undef_action]`
если `undef_action: false` или `undef_action` вообще не определн. сейчас возвращается `true` так как при совпадении первого условия сразу же возвращается `true` и второй экшн не проверяется. верное ли это поведение?

**Comment by the-teacher** [comment]
отлично! мне нравится как ты работаешь =) задавать вопросы это чертовски правильно.
1. Ранее методу `any` передавался хеш `{ pages => new, pages => edit, blogs => index }`
   ожидалось, что метод вернет `true` если роль пользователя обладает секцией `pages` и любое из правил `new` или `edit` равно `true`

те одидается что вот такая штука вернет true

``` ruby
{
  pages: {
    new: false,
    edit: true
  },
  blogs: {
    index: false
  }
}
```

такая тоже вернет true

``` ruby
{
  pages: {
    new: false,
    edit: false
  },
  blogs: {
    index: true
  }
}
```

 только вот такая вернет false

``` ruby
{
  pages: {
    new: false,
    edit: false
  },
  blogs: {
    index: false
  }
}
```

итого
1. any вернет true если есть хотя бы одно правило равное true
2. если найдено правило равное true - то вернем true и другие правила проверятть не будем

**Проблема**

Как оказалось ruby свертывает одинаковые ключи хеша. Я почему то это не увидел в начале. Возможно раньше было другое поведение. Ruby 2.2 точно так делает. Еще и начал ругаться и сыпать warnings

полчучается что предыдущий вариант записи any не жизнеспособный, т.к вместо

`any?({ pages => new, pages => edit, blogs => index })`

фактически я получаю 

`any?({ pages => edit, blogs => index })`

подтому надо изменить формат передачи параметров в метод
и заставить его выполнять ожидаемые действия

новый вид метода будет такой 

``` ruby
any?({ :pages => [ :new, :edit ], :blogs => [ :index ] })
```

вместо

``` ruby
any?({ :pages => :new, :pages => :edit, :blogs => :index })
```

**Comment by sedx** [comment]
Направил PR, но тесты падают, из-за того что DummyApp потягивает TheRole из мастера (без смерженых изменеий).
А еще тесты запускаются только при коммите в DummyApp, но не при коммите в TheRole.
Может быть обратно пересести тесты в TheRole, а DummyApp сделать как Demo приложение? если конечно цель разделения была в том чтобы была отдельная демка.

**Comment by the-teacher** [comment]
1. ты вроде как владелец организации и можешь сам создавать в репах ветки и заливать туда код
2. если задача завязана на несколько частей проекта, то в каждом куске создается ветка с именем задачи
3. Демку можно через гемфайл завязать на конкретные ветки компонент

таким образом, например, можно демку натравить на заданную ветку API и заданнкую ветку UI и развлекаться как угодно.

для тестирования мне будет достаточно перейти на заданную ветку демки, забандлить и запустить тесты или саму демку для прохода по вьюхам.

Примерно так

**Comment by the-teacher** [comment]
Предлагаю ознакомиться с результатами работы

https://travis-ci.org/TheRole/DummyApp/builds/48399073

:+1: :+1: :+1: 

PS: Обрати внимание на тесты с ruby 2.2 - там есть странное предупреждение для тестов для модели User.
